spring: #jdbd configuration
  datasource:
    url: jdbc:mysql://localhost:3306/journalApp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sql@12345

  redis: #cloud configuration
    host: redis-15115.c264.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 15115
    password: 4EB6pmBfLv95uPvAjkEWoB06zNe0ciIs

  mail: #mail configuration
    host: smtp.gmail.com
    port: 587
    username: arbazhusain2023@gmail.com
    password: urhr sqcj kbzc fkss
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable: true

  jpa: #spring-data-jpa-configuration
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    root: error

#logging:
#  level:
#    com:
#      ahusain:
#        journalapp:
#          service:
#            UserService: off for off the logs